#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Basic SDK framework header

#include <cstdint>
#include <cstddef>
#include <type_traits>
#include <utility>
#include <string>

// ----------------------------------------------------------------
// Integer type aliases matching UE / MSVC conventions
// ----------------------------------------------------------------
using uint8  = std::uint8_t;
using uint16 = std::uint16_t;
using uint32 = std::uint32_t;
using uint64 = std::uint64_t;
using int8   = std::int8_t;
using int16  = std::int16_t;
using int32  = std::int32_t;
using int64  = std::int64_t;

// MSVC-style __intN aliases (used in PropertyFixup.hpp and Assertions)
#ifndef _MSC_VER
using __int8  = std::int8_t;
using __int16 = std::int16_t;
using __int32 = std::int32_t;
using __int64 = std::int64_t;
#endif

// ----------------------------------------------------------------
// SDK namespace macros
// ----------------------------------------------------------------
#ifndef SDK_NAMESPACE
#define SDK_NAMESPACE SDK
#endif

#define SDK_NAMESPACE_START namespace SDK_NAMESPACE {
#define SDK_NAMESPACE_END   }

#define SDK_PARAM_NAMESPACE_START namespace Params {
#define SDK_PARAM_NAMESPACE_END   }

// ----------------------------------------------------------------
// Forward declarations of core UE types
// ----------------------------------------------------------------
SDK_NAMESPACE_START

// ----------------------------------------------------------------
// Core UE containers & string types (minimal stubs)
// ----------------------------------------------------------------

class FName
{
public:
	int32 ComparisonIndex;
	int32 Number;
};

struct FStructBaseChain
{
	FStructBaseChain** StructBaseChainArray;
	int32  NumStructBasesInChainMinusOne;
	uint8  Pad[0x4];
};

struct FTextData
{
	uint8 Pad_0[0x20];
	void* TextSource;
	uint8 Pad_28[0x8];
};

class FText
{
public:
	FTextData* TextData;
	uint8 Pad[0x8];
};

class FString
{
public:
	wchar_t* Data;
	int32     Count;
	int32     Max;
};

struct FWeakObjectPtr
{
	int32 ObjectIndex;
	int32 ObjectSerialNumber;
};

struct FUObjectItem
{
	class UObject* Object;
	uint8 Pad[0x10];
};

struct TUObjectArray
{
	FUObjectItem** Objects;
	uint8 Pad_10[0x4];
	int32 MaxElements;
	int32 NumElements;
	int32 MaxChunks;
	int32 NumChunks;
};

template<typename T>
class TArray
{
public:
	T*    Data;
	int32 Count;
	int32 Max;
};

template<typename KeyType, typename ValueType>
class TMap
{
public:
	uint8 Pad[0x50];
};

template<typename T>
class TSet
{
public:
	uint8 Pad[0x50];
};

template<typename Signature>
class TMulticastInlineDelegate
{
public:
	uint8 Pad[0x10];
};

template<typename Signature>
class TMulticastSparseDelegate
{
public:
	uint8 Pad[0x01];
};

template<typename T>
class TSubclassOf
{
public:
	class UClass* ClassPtr;
};

template<typename T>
class TWeakObjectPtr
{
public:
	FWeakObjectPtr WeakPtr;
};

template<typename T>
class TSoftObjectPtr
{
public:
	uint8 Pad[0x28];
};

template<typename T>
class TSoftClassPtr
{
public:
	uint8 Pad[0x28];
};

template<typename T>
class TScriptInterface
{
public:
	void* ObjectPointer;
	void* InterfacePointer;
};

template<typename T>
class TObjectPtr
{
public:
	T* Ptr;
};

template<typename T>
class TLazyObjectPtr
{
public:
	uint8 Pad[0x1C];
};

// ----------------------------------------------------------------
// Core UE object model (minimal definitions for SDK compilation)
// ----------------------------------------------------------------

class UObject
{
public:
	void** VTable;
	uint8  Pad_ObjBase[0x20];

	void ProcessEvent(class UFunction* Function, void* Parms) {}
	static class UClass* StaticClass();
	static const FName& StaticName();
};

class UField : public UObject
{
public:
	uint8 Pad_Field[0x8];
};

class UStruct : public UField
{
public:
	uint8 Pad_Struct[0x60];
	UFunction* GetFunction(const char* ClassName, const char* FuncName) { return nullptr; }
};

class UClass : public UStruct
{
public:
	uint8 Pad_Class[0x1B0];
	static class UClass* FindClass(const char* ClassFullName) { return nullptr; }
};

class UFunction : public UStruct
{
public:
	uint8 Pad_Func[0x30];
};

class UEnum : public UField
{
public:
	uint8 Pad_Enum[0x40];
};

// ----------------------------------------------------------------
// Actor hierarchy stubs
// ----------------------------------------------------------------

class UActorComponent : public UObject
{
public:
	uint8 Pad_ActorComp[0x80];
};

class USceneComponent : public UActorComponent
{
public:
	uint8 Pad_Scene[0x150];
};

class UPrimitiveComponent : public USceneComponent
{
public:
	uint8 Pad_Prim[0x100];
};

class AActor : public UObject
{
public:
	uint8 Pad_Actor[0x1F0];
};

class AInfo : public AActor
{
public:
	uint8 Pad_Info[0x8];
};

class APawn : public AActor
{
public:
	uint8 Pad_Pawn[0x60];
};

class ACharacter : public APawn
{
public:
	uint8 Pad_Character[0xD0];
};

class AController : public AActor
{
public:
	uint8 Pad_Controller[0x50];
};

class APlayerController : public AController
{
public:
	uint8 Pad_PC[0x200];
};

class UUserDefinedStruct : public UStruct
{
public:
	uint8 Pad_UDS[0x20];
};

class UDataAsset : public UObject
{
public:
	uint8 Pad_DA[0x8];
};

class UBlueprintFunctionLibrary : public UObject
{
public:
};

// ----------------------------------------------------------------
// Animation framework stubs
// ----------------------------------------------------------------

class UAnimInstance : public UObject
{
public:
	uint8 Pad_AnimInst[0x3B0];

	class UClass* Class = nullptr;
};

class UAnimNotify : public UObject
{
public:
	uint8 Pad_AN[0x10];
};

class UAnimNotifyState : public UObject
{
public:
	uint8 Pad_ANS[0x18];
};

class UAnimBoneCompressionCodec : public UObject
{
public:
	uint8 Pad_ABCC[0x10];
};

class UAnimCurveCompressionCodec : public UObject
{
public:
	uint8 Pad_ACCC[0x10];
};

// ----------------------------------------------------------------
// Gameplay framework stubs
// ----------------------------------------------------------------

class UBrainComponent : public UActorComponent
{
public:
	uint8 Pad_Brain[0x40];
};

class UCrowdManagerBase : public UObject
{
public:
	uint8 Pad_Crowd[0x10];
};

class UDebugDrawComponent : public UPrimitiveComponent
{
public:
	uint8 Pad_Debug[0x10];
};

class UNavigationQueryFilter : public UObject
{
public:
	uint8 Pad_NQF[0x8];
};

class UMovieSceneSequence : public UObject
{
public:
	uint8 Pad_MSS[0x100];
};

class UMovieSceneSequencePlayer : public UObject
{
public:
	uint8 Pad_MSSP[0x200];
};

class UWidget : public UObject
{
public:
	uint8 Pad_Widget[0x80];
};

// ----------------------------------------------------------------
// Gameplay tasks stubs
// ----------------------------------------------------------------

class UGameplayTask : public UObject
{
public:
	uint8 Pad_GT[0x40];
};

class UGameplayTaskResource : public UObject
{
public:
	uint8 Pad_GTR[0x10];
};

// ----------------------------------------------------------------
// Static class/name helper macros
// ----------------------------------------------------------------

#define STATIC_CLASS_IMPL(ClassName) \
	static class UClass* Clss = nullptr; \
	if (!Clss) Clss = UClass::FindClass(ClassName); \
	return Clss;

#define BP_STATIC_CLASS_IMPL(ClassName) \
	static class UClass* Clss = nullptr; \
	if (!Clss) Clss = UClass::FindClass(ClassName); \
	return Clss;

#define STATIC_NAME_IMPL(NameLiteral) \
	static FName Name{}; \
	return Name;

template<typename T>
T* GetDefaultObjImpl()
{
	return static_cast<T*>(nullptr);
}

// Include assertions
#include "../Assertions.inl"
// Include name collision forward declarations
#include "../NameCollisions.inl"
// Include property fixups
#include "../PropertyFixup.hpp"

SDK_NAMESPACE_END
