#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

#include "Basic.hpp"


SDK_NAMESPACE_START

struct alignas(0x08) FAnimNode_ControlRig
{
	uint8 Pad_FAnimNode_ControlRig[0x4B8];
};


SDK_NAMESPACE_END
