#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

#include "Basic.hpp"


SDK_NAMESPACE_START

// Minimal stub definitions for Engine structs

struct alignas(0x08) FAxis
{
	uint8 Pad_FAxis[0x20];
};

struct alignas(0x01) FFilterOptionPerAxis
{
	uint8 Pad_FFilterOptionPerAxis[0x3];
};

struct alignas(0x08) FVector
{
	uint8 Pad_FVector[0x18];
};

struct alignas(0x08) FVector2D
{
	uint8 Pad_FVector2D[0x10];
};

struct alignas(0x08) FRotator
{
	uint8 Pad_FRotator[0x18];
};

struct alignas(0x10) FQuat
{
	uint8 Pad_FQuat[0x20];
};

struct alignas(0x10) FTransform
{
	uint8 Pad_FTransform[0x60];
};

struct alignas(0x04) FColor
{
	uint8 Pad_FColor[0x4];
};

struct alignas(0x04) FLinearColor
{
	uint8 Pad_FLinearColor[0x10];
};

struct alignas(0x04) FGuid
{
	uint8 Pad_FGuid[0x10];
};

struct alignas(0x08) FHitResult
{
	uint8 Pad_FHitResult[0x100];
};

struct alignas(0x08) FPoseLink
{
	uint8 Pad_FPoseLink[0x10];
};

struct alignas(0x08) FComponentSpacePoseLink
{
	uint8 Pad_FComponentSpacePoseLink[0x10];
};

struct alignas(0x04) FInputScaleBias
{
	uint8 Pad_FInputScaleBias[0x8];
};

struct alignas(0x04) FInputScaleBiasClamp
{
	uint8 Pad_FInputScaleBiasClamp[0x30];
};

struct alignas(0x04) FInputScaleBiasClampConstants
{
	uint8 Pad_FInputScaleBiasClampConstants[0x2C];
};

struct alignas(0x04) FInputClampConstants
{
	uint8 Pad_FInputClampConstants[0x14];
};

struct alignas(0x08) FInputAlphaBoolBlend
{
	uint8 Pad_FInputAlphaBoolBlend[0x48];
};

struct alignas(0x08) FAlphaBlend
{
	uint8 Pad_FAlphaBlend[0x30];
};

struct alignas(0x04) FBoneReference
{
	uint8 Pad_FBoneReference[0x10];
};

struct alignas(0x10) FBoneSocketTarget
{
	uint8 Pad_FBoneSocketTarget[0x90];
};

struct alignas(0x01) FPerPlatformBool
{
	uint8 Pad_FPerPlatformBool[0x1];
};

struct alignas(0x04) FPerPlatformFloat
{
	uint8 Pad_FPerPlatformFloat[0x4];
};

struct alignas(0x04) FPerPlatformInt
{
	uint8 Pad_FPerPlatformInt[0x4];
};

struct alignas(0x08) FPointerToUberGraphFrame
{
	uint8 Pad_FPointerToUberGraphFrame[0x8];
};

struct alignas(0x08) FRichCurve
{
	uint8 Pad_FRichCurve[0x80];
};

struct alignas(0x08) FRuntimeFloatCurve
{
	uint8 Pad_FRuntimeFloatCurve[0x88];
};

struct alignas(0x08) FLatentActionInfo
{
	uint8 Pad_FLatentActionInfo[0x18];
};

struct alignas(0x08) FPoseSnapshot
{
	uint8 Pad_FPoseSnapshot[0x38];
};

struct alignas(0x08) FBranchingPointNotifyPayload
{
	uint8 Pad_FBranchingPointNotifyPayload[0x20];
};

struct alignas(0x08) FAnimNotifyEventReference
{
	uint8 Pad_FAnimNotifyEventReference[0x30];
};

struct alignas(0x08) FConstraintDescriptor
{
	uint8 Pad_FConstraintDescriptor[0x10];
};

struct alignas(0x04) FVectorRK4SpringInterpolator
{
	uint8 Pad_FVectorRK4SpringInterpolator[0x8];
};

struct alignas(0x08) FSoftClassPath
{
	uint8 Pad_FSoftClassPath[0x20];
};

struct alignas(0x08) FNavAgentProperties
{
	uint8 Pad_FNavAgentProperties[0x38];
};

struct alignas(0x08) FTickFunction
{
	uint8 Pad_FTickFunction[0x28];
};

struct alignas(0x08) FAnimSubsystemInstance
{
	uint8 Pad_FAnimSubsystemInstance[0x8];
};

struct alignas(0x08) FAnimSubsystem_Base
{
	uint8 Pad_FAnimSubsystem_Base[0x40];
};

struct alignas(0x08) FAnimSubsystem_PropertyAccess
{
	uint8 Pad_FAnimSubsystem_PropertyAccess[0x80];
};

struct alignas(0x08) FAnimNode_Base
{
	uint8 Pad_FAnimNode_Base[0x10];
};

struct alignas(0x08) FAnimNode_Root : public FAnimNode_Base
{
	uint8 Pad_FAnimNode_Root[0x20];
};

struct alignas(0x08) FAnimNode_StateResult : public FAnimNode_Root
{
	uint8 Pad_FAnimNode_StateResult[0x20];
};

struct alignas(0x08) FAnimNode_TransitionResult
{
	uint8 Pad_FAnimNode_TransitionResult[0x28];
};

struct alignas(0x08) FAnimNode_StateMachine
{
	uint8 Pad_FAnimNode_StateMachine[0xC8];
};

struct alignas(0x08) FAnimNode_SaveCachedPose
{
	uint8 Pad_FAnimNode_SaveCachedPose[0x80];
};

struct alignas(0x08) FAnimNode_UseCachedPose
{
	uint8 Pad_FAnimNode_UseCachedPose[0x28];
};

struct alignas(0x08) FAnimNode_ConvertComponentToLocalSpace
{
	uint8 Pad_FAnimNode_ConvertComponentToLocalSpace[0x20];
};

struct alignas(0x08) FAnimNode_ConvertLocalToComponentSpace
{
	uint8 Pad_FAnimNode_ConvertLocalToComponentSpace[0x20];
};

struct alignas(0x08) FAnimNodeReference
{
	uint8 Pad_FAnimNodeReference[0x10];
};

struct alignas(0x08) FAnimNode_AssetPlayerRelevancyBase
{
	uint8 Pad_FAnimNode_AssetPlayerRelevancyBase[0x10];
};

struct alignas(0x08) FAnimNode_AssetPlayerBase
{
	uint8 Pad_FAnimNode_AssetPlayerBase[0x38];
};

struct alignas(0x08) FAnimNode_SequencePlayer
{
	uint8 Pad_FAnimNode_SequencePlayer[0x48];
};

struct alignas(0x08) FAnimComponentSpacePoseContext
{
	uint8 Pad_FAnimComponentSpacePoseContext[0x10];
};

struct alignas(0x08) FAnimPoseContext
{
	uint8 Pad_FAnimPoseContext[0x10];
};

struct alignas(0x08) FAnimExecutionContext
{
	uint8 Pad_FAnimExecutionContext[0x10];
};

struct alignas(0x08) FAnimInitializationContext
{
	uint8 Pad_FAnimInitializationContext[0x10];
};

struct alignas(0x08) FAnimUpdateContext
{
	uint8 Pad_FAnimUpdateContext[0x10];
};

struct alignas(0x08) FAnimNodeExposedValueHandler_PropertyAccess
{
	uint8 Pad_FAnimNodeExposedValueHandler_PropertyAccess[0x30];
};

struct alignas(0x08) FAnimNodeFunctionRef
{
	uint8 Pad_FAnimNodeFunctionRef[0x20];
};

struct alignas(0x01) FAnimBlueprintConstantData
{
	uint8 Pad_FAnimBlueprintConstantData[0x1];
};

struct alignas(0x01) FAnimBlueprintMutableData
{
	uint8 Pad_FAnimBlueprintMutableData[0x1];
};

struct alignas(0x10) FAnimInstanceProxy
{
	uint8 Pad_FAnimInstanceProxy[0x7A0];
};

struct alignas(0x04) FSimpleIndexedHandleBase
{
	uint8 Pad_FSimpleIndexedHandleBase[0x4];
};

struct alignas(0x08) FConstraintDescriptionEx
{
	uint8 Pad_FConstraintDescriptionEx[0x10];
};

struct alignas(0x08) FInstancedStruct
{
	uint8 Pad_FInstancedStruct[0x10];
};


// Enums

enum class EAlphaBlendOption : uint8 { Default = 0, EAlphaBlendOption_MAX = 1 };
enum class EAnimAlphaInputType : uint8 { Float = 0, Bool = 1, Curve = 2, EAnimAlphaInputType_MAX = 3 };
enum class EAnimGroupRole : uint8 { CanBeLeader = 0, AlwaysFollower = 1, AlwaysLeader = 2, TransitionLeader = 3, TransitionFollower = 4, EAnimGroupRole_MAX = 5 };
enum class EAnimSyncMethod : uint8 { DoNotSync = 0, SyncGroup = 1, Graph = 2, EAnimSyncMethod_MAX = 3 };
enum class EBoneAxis : uint8 { BA_X = 0, BA_Y = 1, BA_Z = 2, BA_MAX = 3 };
enum class EBoneControlSpace : uint8 { BCS_WorldSpace = 0, BCS_ComponentSpace = 1, BCS_ParentBoneSpace = 2, BCS_BoneSpace = 3, BCS_MAX = 4 };
enum class EBoneRotationSource : uint8 { BRS_KeepComponentSpaceRotation = 0, BRS_KeepLocalSpaceRotation = 1, BRS_CopyFromTarget = 2, BRS_MAX = 3 };
enum class EComponentType : uint8 { None = 0, TranslationX = 1, TranslationY = 2, TranslationZ = 3, RotationX = 4, RotationY = 5, RotationZ = 6, Scale = 7, ScaleX = 8, ScaleY = 9, ScaleZ = 10, EComponentType_MAX = 11 };
enum class ECurveBlendOption : uint8 { Override = 0, DoNotOverride = 1, NormalizeByWeight = 2, BlendByWeight = 3, UseBasePose = 4, UseMaxValue = 5, UseMinValue = 6, ECurveBlendOption_MAX = 7 };
enum class EAxis : uint8 { None = 0, X = 1, Y = 2, Z = 3, EAxis_MAX = 4 };
enum class EDrawDebugTrace : uint8 { None = 0, ForOneFrame = 1, ForDuration = 2, Persistent = 3, EDrawDebugTrace_MAX = 4 };
enum class EEndPlayReason : uint8 { Destroyed = 0, LevelTransition = 1, EndPlayInEditor = 2, RemovedFromWorld = 3, Quit = 4, EEndPlayReason_MAX = 5 };
enum class ECollisionChannel : uint8 { ECC_WorldStatic = 0, ECC_WorldDynamic = 1, ECC_Pawn = 2, ECC_Visibility = 3, ECC_Camera = 4, ECC_PhysicsBody = 5, ECC_MAX = 6 };
enum class ETraceTypeQuery : uint8 { TraceTypeQuery1 = 0, TraceTypeQuery_MAX = 1 };
enum class ERelativeTransformSpace : uint8 { RTS_World = 0, RTS_Actor = 1, RTS_Component = 2, RTS_ParentBoneSpace = 3, RTS_MAX = 4 };
enum class EMovementMode : uint8 { MOVE_None = 0, MOVE_Walking = 1, MOVE_NavWalking = 2, MOVE_Falling = 3, MOVE_Swimming = 4, MOVE_Flying = 5, MOVE_Custom = 6, MOVE_MAX = 7 };
enum class ETransitionLogicType : uint8 { TLT_StandardBlend = 0, TLT_Inertialization = 1, TLT_MAX = 2 };
enum class EAnimExecutionContextConversionResult : uint8 { Succeeded = 0, Failed = 1, EAnimExecutionContextConversionResult_MAX = 2 };
enum class EAnimNodeReferenceConversionResult : uint8 { Succeeded = 0, Failed = 1, EAnimNodeReferenceConversionResult_MAX = 2 };
enum class EAnimPhysCollisionType : uint8 { CoM = 0, CustomSphere = 1, InnerSphere = 2, OuterSphere = 3, EAnimPhysCollisionType_MAX = 4 };
enum class EAnimPhysTwistAxis : uint8 { AxisX = 0, AxisY = 1, AxisZ = 2, EAnimPhysTwistAxis_MAX = 3 };

// Forward-declared classes

class AVolume;
class ANavigationData;
class ARecastNavMesh;
class UAnimMontage;
class UAnimSequence;
class UAnimSequenceBase;
class UAnimationAsset;
class UBlendProfile;
class UBlendSpace;
class UCharacterMovementComponent;
class UCharacterMoverComponent;
class UCommonLegacyMovementSettings;
class UCurveFloat;
class UGameplayTasksComponent;
class UMirrorDataTable;
class UNavLinkCustomComponent;
class UNavMovementComponent;
class UNavigationPath;
class UPhysicalMaterial;
class UPhysicsAsset;
class UPoseAsset;
class UScriptStruct;
class USkeletalMesh;
class USkeletalMeshComponent;
class USkeleton;
class USoundBase;
class UWorld;

// Game-specific forward declarations
class ABP_AI_Base_C;
class ABP_BigPenAI_C;
class ABP_FirstPersonCharacter_LINK_C;
class AEnemy_AI_Base_C;
class UBPC_MovementModeControl_C;
class UBPC_ReplicateAnimBPState_C;
class UBP_FootStepSoundPreset_C;

// Additional engine base classes

class UAISystemBase : public UObject
{
public:
    uint8 Pad_AISB[0x10];
};

class UBaseGeneratedNavLinksProxy : public UObject
{
public:
    uint8 Pad_BGNLP[0x10];
};

// Enum for surface type
enum class EPhysicalSurface : uint8 { SurfaceType_Default = 0, EPhysicalSurface_MAX = 1 };

SDK_NAMESPACE_END
