#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

#include "Basic.hpp"


SDK_NAMESPACE_START

struct alignas(0x04) FGameplayTag
{
	uint8 Pad_FGameplayTag[0x8];
};

struct alignas(0x08) FGameplayTagContainer
{
	uint8 Pad_FGameplayTagContainer[0x20];
};

struct alignas(0x08) FGameplayTagQuery
{
	uint8 Pad_FGameplayTagQuery[0x48];
};

struct alignas(0x02) FGameplayResourceSet
{
	uint8 Pad_FGameplayResourceSet[0x2];
};


enum class EGameplayContainerMatchType : uint8 { Any = 0, All = 1, EGameplayContainerMatchType_MAX = 2 };

SDK_NAMESPACE_END
