#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

#include "Basic.hpp"


SDK_NAMESPACE_START

struct alignas(0x04) FMovieSceneSequencePlaybackSettings
{
	uint8 Pad_FMovieSceneSequencePlaybackSettings[0x28];
};


class UMovieScene;

SDK_NAMESPACE_END
