#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

#include "Basic.hpp"


SDK_NAMESPACE_START

struct alignas(0x08) FSlateWidgetStyle
{
	uint8 Pad_FSlateWidgetStyle[0x8];
};

struct alignas(0x10) FSlateBrush
{
	uint8 Pad_FSlateBrush[0xB0];
};

struct alignas(0x10) FSliderStyle : public FSlateWidgetStyle
{
	uint8 Pad_FSliderStyle[0x440];
};


SDK_NAMESPACE_END
